### ISSUE TITLE
[BUG]: Crash

### ISSUE THREAD

**Issue by SrYthan** [Thorfusion/Mekanism-Community-Edition#113] opened 2023-04-19 02:21 UTC
### Describe the bug

I don't know the exact reason, but apparently it's when unloading chunks

### To Reproduce

just leaving the site with machines causes the crash

### Expected behavior

may be caused by ghost chunk loading issue

### Mekanism Version

9.10.27

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Linux

### Name of modpack if applicable

A Era do Futuro V3 TotalCraft

### The crash report in folder ./crash-reports (both server and client logs)

[crash-2023-05-10_12.50.29-server.txt](https://github.com/Thorfusion/Mekanism-Community-Edition/files/11574836/crash-2023-05-10_12.50.29-server.txt)

[crash-2023-05-13_19.31.25-server.txt](https://github.com/Thorfusion/Mekanism-Community-Edition/files/11574837/crash-2023-05-13_19.31.25-server.txt)

### Please provide the following other files
[2023-05-10-2.log](https://github.com/Thorfusion/Mekanism-Community-Edition/files/11574885/2023-05-10-2.log)

[2023-05-13-2.log](https://github.com/Thorfusion/Mekanism-Community-Edition/files/11574905/2023-05-13-2.log)

**Comment by maggi373** [comment] 2023-05-16 11:22
please provide the full crash log provided in ./crash-reports and the log in /logs, as per form described you to do

**Comment by maggi373** [comment] 2023-05-24 01:11
closing due to not following the template and not responding about requested files and not reproducable

**Comment by SrYthan** [comment] 2023-05-26 11:10
sorry for the incomplet issue, i go to edit this now

**Comment by SrYthan** [comment] 2023-05-26 11:54
I edited the Issue and put the files you requested, sorry for the misunderstanding

**Comment by maggi373** [comment] 2023-05-26 11:59
https://maven.thorfusion.com/artifactory/dev/mekanism/Mekanism-Community-Edition/1.7.10-9.10.28-342/Mekanism-Community-Edition-1.7.10-9.10.28-342-ALL.jar test with this

**Comment by maggi373** [comment] 2023-05-26 20:19
try the latest release, it has the same fix as in previous coment

**Comment by SrYthan** [comment] 2023-05-27 17:12
ok, i go to try this version, thanks!

**Comment by SrYthan** [comment] 2023-06-04 16:05
I installed the latest version to test the crash, and now my server doesn't open anymore, and even going back to the version I was using always causes the same crash when connecting the server.
![crash mekanism 1 7 10](https://github.com/Thorfusion/Mekanism-Community-Edition/assets/78868186/1ea4795b-fe32-40e6-97cd-70e5c8f6b060)

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1498)
	at mekanism.common.Mekanism.onChunkLoad(Mekanism.java:1686)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_701_Mekanism_onChunkLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1054)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:213)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:186)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:324)
	at net.minecraft.world.World.func_72964_e(World.java:779)
	at net.minecraft.world.World.func_147438_o(World.java:3190)
	at powercrystals.minefactoryreloaded.net.CommonProxy.loadTicket(CommonProxy.java:38)
	at powercrystals.minefactoryreloaded.net.CommonProxy.ticketsLoaded(CommonProxy.java:54)
	at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:542)
	at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_13_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:444)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641)
	at java.lang.Thread.run(Thread.java:750)

**Comment by maggi373** [comment] 2023-06-27 14:38
can we get the world file? also join our discord server as this is a very unusual issue, i will make a special build for you that might allow you to boot up the server again but this is a modpack sepcific issue and you need to find the mod that is doing shit when mek is doing shit

**Comment by maggi373** [comment] 2023-06-27 14:47
you also have alot of other errors, aswell as using gtnh which isnt tested against mek and running some form of kcauldron/thermos/crucible with plugins. run the world in singleplayer, if its not crashing, close the issue. as its nothing we can do at that point

**Comment by SrYthan** [comment] 2023-06-27 15:33
Sorry for the delay in replying, gmail didn't even notify me that they replied, well I managed to solve it on my own, I downloaded the src from mek ce and edited the part that caused the error when connecting, in this case I removed the verification of the TileEntity TileEntityElectricBlock
This solved it and I managed to connect the server, right after I put the last version again and until then the error occurs a few times but the server manages to connect again without problem.
I am grateful for the intention to help me, the only error I get is this one from the onChunkLoad method that occurs sometimes, but I believe it is due to the 1.7.10 bug about GhostChunkLoading and that ends up causing this crash.


@SubscribeEvent
	public synchronized void onChunkLoad(ChunkEvent.Load event)
	{
		if(event.getChunk() != null && !event.world.isRemote)
		{
			//Map copy = (Map)((HashMap)event.getChunk().chunkTileEntityMap).clone();

			for(Iterator iter = /*copy*/event.getChunk().chunkTileEntityMap.values().iterator(); iter.hasNext();)
			{
				Object obj = iter.next();

				if(obj instanceof TileEntity)
				{
					TileEntity tileEntity = (TileEntity)obj;

					//if(tileEntity instanceof TileEntityElectricBlock && MekanismUtils.useIC2())
					//{
					//	((TileEntityElectricBlock)tileEntity).register();
					//}
					//else if(tileEntity instanceof IChunkLoadHandler)
					//{
					//	((IChunkLoadHandler)tileEntity).onChunkLoad();
					//}
				}
			}
		}
	}

**Comment by DrParadox7** [comment] 2023-09-21 15:11
Please try see if the crash still occurs with the experimental release in #141

**Comment by SrYthan** [comment] 2023-09-21 20:49
Rught, i Go to try this and send you If work, thanks my brother.

**Comment by DrParadox7** [comment] 2023-09-24 15:31
@SrYthan Any updates?

**Comment by FnTlv** [comment] 2023-09-28 10:31
@DrParadox7 https://github.com/Thorfusion/Mekanism-Community-Edition/pull/141 I had the same problem and the crash doesn't happen again after I use this version

**Comment by maggi373** [comment] 2023-10-18 11:51
fixed by #141

**Closed as completed by maggi373** 2023-10-18 11:51 UTC
Labels: TYPE: BUG, STATUS: Can't replicate, MC: 1.7.10, PRIORITY: N/A
