### ISSUE TITLE
[BUG]: Crash with Waila

### ISSUE THREAD

**Issue by xJon** [Thorfusion/Mekanism-Community-Edition#109] opened 2023-03-31 14:49 UTC
### Describe the bug

Seems to have occurred randomly upon entering into a world.

### To Reproduce

Not sure.

### Expected behavior

No crash.

### Mekanism Version

9.8.3.390

### Minecraft Version is this regarding?

1.12.2

### The crash report in folder ./crash-reports (both server and client logs)

https://mclo.gs/gG1hyHG

**Comment by HaHaWTH** [comment] 2023-04-08 10:49
> ### Describe the bug
> Seems to have occurred randomly upon entering into a world.
> 
> ### To Reproduce
> Not sure.
> 
> ### Expected behavior
> No crash.
> 
> ### Mekanism Version
> 9.8.3.390
> 
> ### Minecraft Version is this regarding?
> 1.12.2
> 
> ### The crash report in folder ./crash-reports (both server and client logs)
> https://mclo.gs/gG1hyHG

I think you should unload LoliASM and try to update your Java version then test again , 8u50 is too old and LoliASM has many serious bugs

**Comment by maggi373** [comment] 2023-04-08 10:51
8u50 is what technic launcher uses and it is an issue having so old java

**Comment by maggi373** [comment] 2023-05-24 01:15
closing due to #103 is the same npe and the other crash is reproducable while this is not

**Closed as completed by maggi373** 2023-05-24 01:15 UTC
Labels: TYPE: BUG, MC: 1.12.2, STATUS: NOT STARTED, PRIORITY: N/A
