### ISSUE TITLE
Graphic glitch issue between cable and digital miner

### ISSUE THREAD

**Issue by quentin452** [Thorfusion/Mekanism-Community-Edition#41] opened 2022-10-03 21:26 UTC
**Describe the bug**

graphic glitch issue between cable and digital miner
we see green lines, when we shouldn't see them

**To Reproduce**

1. use a cable and digital miner
2. coonnect the cable to the digital miner
3. watch the graphic glitch

**Expected behavior**

just a glitch issue(green lines)

**Screenshots**

![Capture d’écran_2022-10-03_23-23-28](https://user-images.githubusercontent.com/42176772/193685333-af1fd720-9965-461a-a655-29148461cf86.png)

**Desktop (please complete the following information):**
 - OS: Endeavour os(arch linux)
 - Modpack: (none)
 - Modpack Version: (none)
 - Mekanism 1.7.10-9.10.16-ALL
 - Forge Version: 10.13.4.1614
 

 **Mods list : **
 
 - CodeChickenCore-1.7.10-1.1.6,
 - CodeChickenLib-1.7.10-1.1.5.5,
 - ForgeMultipart-1.7.10-1.2.9,
 - Mekanism-1.7.10-Community-Edition-1.7.10-9.10.16-ALL

**Comment by maggi373** [comment] 2022-10-03 21:30
this is more of an issue in general with minecraft and it most likely wont be fixed. need to do some research first before closing the issue

**Comment by quentin452** [comment] 2022-10-03 21:30
ok

**Comment by DrParadox7** [comment] 2022-10-20 19:18
Not a bug.
This is just a feature of MC rendering.

**Comment by maggi373** [comment] 2022-11-19 16:02
won't fix

**Closed as not planned by maggi373** 2022-11-19 16:02 UTC
Labels: TYPE: ENHANCEMENT, STATUS: wontfix, PRIORITY: LOW, STATUS: ON HOLD, MC: 1.7.10
