### ISSUE TITLE
[BUG] Weird white overlay on machines

### ISSUE THREAD

**Issue by Jerome226** [Thorfusion/Mekanism-Community-Edition#25] opened 2022-03-08 05:54 UTC
**Describe the bug**
When placing most machines (exceptions of the factories) you can see a weird white overlay in top of the machines, making them looks weird.                    

**To Reproduce**
1. Open Game
2. Load a world
3. Check texture

**Expected behavior**
That the machine would have the normal Mekanism texture

**Screenshots**
![image](https://user-images.githubusercontent.com/55724525/157174807-5fcf9df9-2f43-40b1-b6ea-321b5c126f7e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Modpack: Custom
 - Modpack Version: 1.7.10
 - Mekanism Version: 9.10.11
 - Forge Version: 1614

**Comment by maggi373** [comment] 2022-03-08 06:22
i am unable to reproduce this issue, we've had a similar bug in our pack but it was unreleated to mekanism

**Comment by Jerome226** [comment] 2022-03-09 02:14
I see, probably is Optifine fault.

**Comment by maggi373** [comment] 2022-03-09 02:16
for 1.7.10 optifine is shit, our pack it almost decreases the performancy by half and has alot of stutters

**Comment by Jerome226** [comment] 2022-03-09 02:17
For me optifine is kinda good, but I'm not playing the same pack 🤷‍♀️

**Comment by maggi373** [comment] 2022-03-09 02:19
fair enough, but i dont recommend using it on any version, had only bad experiences and with sodium, phosphor n stuff, optifine is outdated anyway

**Comment by maggi373** [comment] 2022-03-09 02:20
seems that we had this problem back in 2015, a bit unsure, we didnt save our bugreports n stuff when i began making my own modpack in january 2014

**Comment by Jerome226** [comment] 2022-03-09 02:20
Well, 1.7 is also like 8 years old so using outdated stuff shouldn't be an issue, but I will still test without it and tell you if it's the issue.

**Comment by maggi373** [comment] 2022-03-09 02:22
y, good luck, it might not be optifine. close the issue if you find what causes it and its not related to the mod.

**Comment by maggi373** [comment] 2022-04-25 01:32
30+ days since last response

**Closed as completed by maggi373** 2022-04-25 01:33 UTC
Labels: invalid

**Comment by embeddedt** [comment] 2023-01-01 02:51
This is still an issue with 9.10.22. To reproduce you just need to load an instance with Mekanism and the [Modernity](https://www.curseforge.com/minecraft/texture-packs/modernity) texture pack installed. Blocks such as the crusher will then have white sides.

**Comment by DrParadox7** [comment] 2023-01-02 00:32
> This is still an issue with 9.10.22. To reproduce you just need to load an instance with Mekanism and the [Modernity](https://www.curseforge.com/minecraft/texture-packs/modernity) texture pack installed. Blocks such as the crusher will then have white sides.

This is an issue with Modernity for it retextures those blocks.
The way AstroTibs compresses textures in the pack is too aggressive, which is what's causing those issues.

**Comment by DrParadox7** [comment] 2023-01-02 00:53
Here, you can see it yourself:
[Proof of Work.zip](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10329757/Proof.of.Work.zip)
All I did in this resource pack is to force all Mekanism texture used by Modernity to RGB.
The problem disappears. You can go in game and try it out.

**Comment by embeddedt** [comment] 2023-01-02 02:58
Thank you for looking into this @DrParadox7! I'll just add this texture pack on top of Modernity for now until the issue is fixed.
